strategy:
  _target_: dasha.strategy.MarinaAggregator
  step_size: ???

client:
  _target_: dasha.client.MarinaClient
  device: cpu
  evaluate_accuracy: false
  send_gradient: false
  strict_load: true