strategy:
  _target_: dasha.strategy.MarinaAggregator
  step_size: 0.5
  size_of_compressed_vectors: ???

client:
  _target_: dasha.client.MarinaClient
  device: cpu
  evaluate_accuracy: true
  send_gradient: true