num_clients: 5
num_rounds: 100

client_resources:
  num_cpus: 2
  num_gpus: 0.0

model:
  _target_: dasha.models.LinearNetWithNonConvexLoss
  num_input_features: 112
  init_with_zeros: True

# compressor:
#   _target_: dasha.compressors.RandKCompressor
#   number_of_coordinates: 10

compressor:
  _target_: dasha.compressors.IdentityUnbiasedCompressor

strategy:
  _target_: dasha.strategy.DashaAggregator
  step_size: 0.5

client:
  _target_: dasha.client.DashaClient
  device: cpu
  evaluate_accuracy: true

defaults:
  - dataset: libsvm