num_clients: 5
num_rounds: 10000
save_path: !!null

client_resources:
  num_cpus: 2
  num_gpus: 0.0

model:
  _target_: dasha.models.LinearNetWithNonConvexLoss
  num_input_features: 112
  init_with_zeros: True

compressor:
  _target_: dasha.compressors.RandKCompressor
  number_of_coordinates: 10

defaults:
  - dataset: libsvm
  - method: dasha