num_clients: 5
num_rounds: 10000
save_path: !!null

client_resources:
  num_cpus: 2
  num_gpus: 0.0

compressor:
  _target_: dasha.compressors.RandKCompressor
  number_of_coordinates: ???

defaults:
  - dataset: libsvm
  - method: dasha
  - model: linear_net_with_non_convex_loss