num_clients: 10
num_rounds: 100

client_resources:
  num_cpus: 2
  num_gpus: 0.0

model:
  # model config

strategy:
  _target_: dasha.strategy.DashaStrategy
  step_size: 0.01

client:
  _target_: dasha.client.DashaClient
  device: 'cpu'

defaults:
  - dataset: libsvm